watsonx:
  model_id: "ibm/granite-13b-chat-v1"
  api_key: ${WATSONX_API_KEY}
  url: ${WATSONX_URL}
  project_id: ${WATSONX_PROJECT_ID}

llm:
  temperature: 0.7
  max_tokens: 1000

streamlit:
  page_title: "WatsonX AI Project Assistant"
  page_icon: "🤖"
